language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23

notifications:
  email: false
  slack: cinebuff:8XllnTACl1gXpIUfPGMLr4qL

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
#install: ./gradlew clean build
script: ./gradlew check