language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-21
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23

notifications:
  email: false
  slack: cinebuff:8XllnTACl1gXpIUfPGMLr4qL

before_install:

  # for gradle output style
  - export TERM=dumb

  # environment info
  - ./gradlew -v
  - uname -a

# Let's try to build...
#install: ./gradlew clean build
script: ./gradlew check

after_success:
  - bash <(curl -s https://codecov.io/bash)